### ISSUE TITLE
Unable to connect with build function

### ISSUE THREAD

**Issue by tkslabz** [webservices-nl/platform-connector#8]
Hello,
I have written a sample code to connect with Webservices.nl API, I have used the code which is present on https://github.com/webservices-nl/platform-connector. But it is showing me an errro  Fatal error: Class 'ConnectorFactory' not found. Could you please help me to sortout this error?

**Comment by kanariezwart** [comment]
Hello,

It looks like your application cannot find the factory code. Do you have an autoloader setup? Can you provide us with an dump of your composer file?
